backend/modules/ProblemReports/models/ProblemReports.php
<?php

namespace backend\modules\ProblemReports\models;

use Yii;
use yii\helpers\Url;
use yii\helpers\Html;
/* need for file upload */
use backend\modules\YiiFileManager\models\File;
use backend\modules\YiiFileManager\models\Folders;
use backend\modules\YiiFileManager\models\FileAction;

/**
 * This is the model class for table "problem_reports".
 *
 * @property integer $id
 * @property integer $userId
 * @property integer $eventId
 * @property string $problemTitle
 * @property string $problemDescription
 * @property integer $imgId1
 * @property integer $imgId2
 * @property integer $imgId3
 * @property string $problemPage
 * @property integer $status
 * @property integer $important
 * @property string $response
 * @property string $requestDate
 * @property string $statusChangeDate
 * @property integer $valid
 */
class ProblemReports extends \yii\db\ActiveRecord {
	public $fileImg1;
	public $fileImg2;
	public $fileImg3;
	/**
	 * @inheritdoc
	 */
	public static function tableName() {
		return '{{%problem_reports}}';
	}
	/**
	 * @inheritdoc
	 *
	 * @return ProvinceQuery the active query used by this AR class.
	 */
	public static function find() {
		return new ProblemReportsQuery( get_called_class () );
	}
	/**
	 *
	 * @var Status
	 */
	const Status_Unread = 1;
	const Status_Read = 2;
	const Status_Pending = 3;
	const Status_Done = 4;
	const Status_list = [ 
			self::Status_Unread => 'Unread',
			self::Status_Read => 'Read',
			self::Status_Pending => 'Pending',
			self::Status_Done => 'Done' 
	];
	/**
	 *
	 * @var Important
	 */
	const Important_Necessary = 1;
	const Important_Average = 2;
	const Important_UnNecessary = 3;
	const Important_list = [ 
			self::Important_Necessary => 'Necessary',
			self::Important_Average => 'Average',
			self::Important_UnNecessary => 'UnNecessary' 
	];
	
	/**
	 * @inheritdoc
	 */
	public function rules() {
		$fileModel = new File ();
		return [ 
				[ 
						[ 
								'userId',
								'eventId',
								'problemTitle',
								'problemDescription',
								'status' 
						],
						'required' 
				],
				[ 
						[ 
								'userId',
								'eventId',
								'imgId1',
								'imgId2',
								'imgId3',
								'status',
								'important',
								'valid' 
						],
						'integer' 
				],
				[ 
						[ 
								'problemDescription',
								'response' 
						],
						'string' 
				],
				[ 
						[ 
								'requestDate',
								'statusChangeDate' 
						],
						'safe' 
				],
				[ 
						[ 
								'problemTitle',
								'problemPage' 
						],
						'string',
						'max' => 255 
				],
				[ 
						[ 
								'fileImg1',
								'fileImg2',
								'fileImg3' 
						],
						'file',
						'skipOnEmpty' => true,
						'extensions' => 'jpg,jpeg,png',
						'checkExtensionByMimeType' => true,
						'maxSize' => File::MAX_FILE_SIZE,
						'tooBig' => " حداکثر اندازه فایل باید " . $fileModel->humanReadableFileSize ( File::MAX_FILE_SIZE ) . '  باشد',
						'tooSmall' => "حداقل اندازه فایل باید  " . $fileModel->humanReadableFileSize ( File::MIN_FILE_SIZE ) . '  باشد',
						'minSize' => File::MIN_FILE_SIZE,
						'mimeTypes' => [ 
								'image/jpeg',
								'image/jpg',
								'image/png' 
						] 
				] 
		];
	}
	
	/**
	 * @inheritdoc
	 */
	public function attributeLabels() {
		return [ 
				'id' => Yii::t ( 'app', 'ID' ),
				'userId' => Yii::t ( 'app', 'User ID' ),
				'eventId' => Yii::t ( 'app', 'Event ID' ),
				'problemTitle' => Yii::t ( 'app', 'Problem Title' ),
				'problemDescription' => Yii::t ( 'app', 'Problem Description' ),
				'imgId1' => Yii::t ( 'app', 'Img Id1' ),
				'imgId2' => Yii::t ( 'app', 'Img Id2' ),
				'imgId3' => Yii::t ( 'app', 'Img Id3' ),
				'problemPage' => Yii::t ( 'app', 'Problem Page' ),
				'status' => Yii::t ( 'app', 'Status' ),
				'important' => Yii::t ( 'app', 'Important' ),
				'response' => Yii::t ( 'app', 'Response' ),
				'requestDate' => Yii::t ( 'app', 'Request Date' ),
				'statusChangeDate' => Yii::t ( 'app', 'Status Change Date' ),
				'valid' => Yii::t ( 'app', 'Valid' ),
				'fileImg1' => Yii::t ( 'app', 'fileImg1' ),
				'fileImg2' => Yii::t ( 'app', 'fileImg2' ),
				'fileImg3' => Yii::t ( 'app', 'fileImg3' ) 
		];
	}
	/**
	 * *
	 */
	public function beforeValidate() {
		/**
		 * eventId
		 */
		if (isset ( Yii::$app->user->identity->eventId ))
			$this->eventId = Yii::$app->user->identity->eventId;
		else {
			throw new \yii\web\HttpException ( 400, Yii::t ( 'app', 'The Security error' ) );
		}
		/**
		 * *
		 */
		if (is_null ( $this->important ))
			$this->important = self::Important_Average;
		/**
		 */
		if($this->isNewRecord)
			$this->userId = Yii::$app->user->identity->id;
		else if (Yii::$app->user->can ( 'SeniorUserEvent' ))
			$this->responseUserId= Yii::$app->user->identity->id;
		/**
		 */
		if ($this->isNewRecord)
			$this->status = self::Status_Unread;
		return parent::beforeValidate ();
	}
	/**
	 * *
	 */
	public static function StatusFa($status = 0, $all = false) {
		if ($all == true) {
			$array = [ ];
			foreach ( self::Status_list as $key => $value )
				$array [$key] = Yii::t ( 'app', $value );
			return $array;
		} else {
			if (array_key_exists ( $status, self::Status_list ))
				return \Yii::t ( 'app', self::Status_list [$status] );
			else
				return Yii::t ( 'zii', 'Not set' );
		}
	}
	/**
	 * *
	 */
	public static function ImportantFa($status = 0, $all = false) {
		if ($all == true) {
			$array = [ ];
			foreach ( self::Important_list as $key => $value )
				$array [$key] = Yii::t ( 'app', $value );
			return $array;
		} else {
			if (array_key_exists ( $status, self::Important_list ))
				return \Yii::t ( 'app', self::Important_list [$status] );
			else
				return Yii::t ( 'zii', 'Not set' );
		}
	}
	/**
	 * *
	 */
	public function getRequestDateFa() {
		return ($this->requestDate != '0000-00-00 00:00:00') ? Yii::$app->jdate->date ( 'Y/m/d', strtotime ( $this->requestDate ) ) : Yii::t ( 'zii', 'Not set' );
	}
	/**
	 * *
	 */
	public function getStatusChangeDateFa() {
		return ($this->statusChangeDate != '0000-00-00 00:00:00') ? Yii::$app->jdate->date ( 'Y/m/d', strtotime ( $this->statusChangeDate ) ) : Yii::t ( 'zii', 'Not set' );
	}
	/**
	 * *
	 */
	public function getStatusUI() {
		$color = '';
		$icon = '';
		switch ($this->status) {
			case self::Status_Unread :
				$color = 'danger';
				$icon = 'icon-badge';
				break;
			case self::Status_Read :
				$color = 'warning';
				$icon = 'icon-badge';
				break;
			case self::Status_Pending :
				$color = 'info';
				$icon = 'icon-badge';
				break;
			case self::Status_Done :
				$icon = 'icon-badge';
				$color = 'success';
				break;
			default :
				$color = 'default';
				$color = 'blue-steel';
				break;
		}
		$index = $this->status;
		return '<span class="badge badge-' . $color . '"><i class="' . $icon . '"></i></span>';
	}
	/**
	 */
	public static function CountStatus($status = NULL) {
		if ($status == null)
			return 0;
		if (array_key_exists ( $status, self::Status_list ))
			return self::find ()->where ( [ 
					'status' => $status 
			] )->count ();
		else
			return 0;
	}
	/**
	 */
	public function uploadPicFile($fileImg = 0, $attributeImg = 0) {
		// if (is_null ( $fileImg ) || is_null ( $attributeImg ) || empty ( trim($fileImg) ) || empty ( trim($attributeImg) ) || $fileImg == 0 || $attributeImg == 0)
		// return true;
		$fileModel = new File ();
		$fileModel->scenario = File::MODEL_FILE_UPLOAD_SCENARIO;
		$fileModel->modelFileTyps = 'jpg,jpeg,png';
		$fileModel->modelMimeFileTyps = [ 
				'image/jpeg',
				'image/jpg',
				'image/png' 
		];
		$fileModel->modelFileskipOnEmpty = true;
		$fileModel->modelFileSize = File::MAX_FILE_SIZE;
		/**
		 * Add icon file*
		 */
		
		$fileModel->folder_id = Folders::SPORT_LOCATION_FOLDER_ID;
		$fileModel->model_id = $this->id;
		$fileModel->model_type = 'ProblemReports';
		$fileModel->temporaryFileAttr = \yii\web\UploadedFile::getInstance ( $this, $fileImg );
		
		if ($fileModel->temporaryFileAttr != null) {
			
			if ($fileModel->validate () && $fileModel->uploadModelFile ( 'ProblemReports' . $fileImg . '_' . $this->id )) {
				
				/* remove old file in edit action call */
				$Select_Img = '';
				switch ($attributeImg) {
					case 'imgId1' :
						$Select_Img = $this->imgId1;
						break;
					case 'imgId2' :
						$Select_Img = $this->imgId2;
						break;
					case 'imgId3' :
						$Select_Img = $this->imgId3;
						break;
				}
				if (isset ( $Select_Img )) {
					$oldFileId = $Select_Img;
					if (($oldFileModel = FileAction::findOne ( $oldFileId )) !== null) {
						$oldFileModel->removeFile ( $oldFileId );
					}
				}
				
				/* save file id in categorie table */
				switch ($attributeImg) {
					case 'imgId1' :
						$this->imgId1 = ( int ) $fileModel->id;
						break;
					case 'imgId2' :
						$this->imgId2 = ( int ) $fileModel->id;
						break;
					case 'imgId3' :
						$this->imgId3 = ( int ) $fileModel->id;
						break;
				}
				$this->update ( 0 );
				return true;
			} else {
				if (count ( $fileModel->errors ) > 0) {
					$msg = '';
					foreach ( $fileModel->errors as $attribute => $errors ) {
						foreach ( $errors as $error ) {
							$msg .= $error;
						}
					}
					$this->addError ( $fileImg, $msg );
					return false;
				}
			}
		}
		return true;
	}
	
	public function getIconThumbnail($numberImg, $fileId = null, $class = '', $width = '45px', $height = '45px') {
		if (isset ( $fileId )) {
			switch (( int ) $numberImg) {
				case 1 :
					$this->imgId1 = $fileId;
					break;
				case 2 :
					$this->imgId2 = $fileId;
					break;
				case 3 :
					$this->imgId3 = $fileId;
					break;
			}
		}
		
		/* find file of categories in db */
		$filemodel = null;
		switch (( int ) $numberImg) {
			case 1 :
				$filemodel = File::findOne ( $this->imgId1 );
				break;
			case 2 :
				$filemodel = File::findOne ( $this->imgId2 );
				break;
			case 3 :
				$filemodel = File::findOne ( $this->imgId3 );
				break;
		}
		if (! is_null ( $filemodel )) {

backend/modules/ProblemReports/views/problem-reports/CopyOf_formResponse.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\modules\ProblemReports\models\ProblemReports */
/* @var $form yii\widgets\ActiveForm */

use yii\web\JsExpression;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use kartik\select2\Select2;
use yii\base\Widget;
use kartik\file\FileInput;
use backend\modules\ProblemReports\models\ProblemReports;

$formGroupClass = Yii::$app->params ['formGroupClass'];
$template = '{label}<div class="col-md-9 col-sm-9">{input} {hint} {error}</div>';
$template_4 = Yii::$app->params ['template_4'];
$inputClass = Yii::$app->params ['inputClass'];
$labelClass = 'col-md-3 col-sm-3 control-label';
$labelClass_min = 'col-md-2 col-sm-2 control-label';
$errorClass = Yii::$app->params ['errorClass'];
?>
<div class="col-md-12 col-sm-12 col-xs-12">
	<div class='form-group'>
		<div class="caption">
			<i class="fa fa-reply "></i> <span
				class="caption-subject  bold uppercase"><?php echo Yii::t('app','Response');?></span>
			<hr>
		</div>
	</div>
</div>

<div class='row'>
	<div class='form-group'>
			<?php
			echo $form->field ( $model, 'status', [ 
					'options' => [ 
							'class' => $formGroupClass 
					],
					'template' => '{label}<div class="col-md-9 col-sm-9"><div class="btn-group" data-toggle="buttons" id="fields-gametype">{input} </div> {hint} {error}</div>' 
			] )->radioList ( ProblemReports::StatusFa ( 0, true ), [ 
					'tag' => false,
					'unselect' => NULL,
					'item' => function ($index, $label, $name, $checked, $value) {
						return '<label class="btn btn-info ' . ($checked ? 'active' : '') . '">' . Html::radio ( $name, $checked, [ 
								'value' => $value,
								'autocomplete' => 'off' 
						] ) . $label . '</label>';
					} 
			] )->label ( NULL, [ 
					'class' => $labelClass_min 
			] );
			?>
	</div>
</div>

<div class='row'>
	<div class='form-group'>
	<?php
	echo $form->field ( $model, 'response', [ 
			'options' => [ 
					'class' => $formGroupClass 
			],
			'template' => $template 
	] )->textarea ( [ 
			'class' => $inputClass,
			'rows' => 10 
	] )->label ( NULL, [ 
			'class' => $labelClass_min 
	] );
	?>
	</div>
</div>

backend/modules/ProblemReports/views/problem-reports/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\modules\ProblemReports\models\ProblemReportsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="problem-reports-search">

	<?php $form = ActiveForm::begin([
		'action' => ['index'],
		'method' => 'get',
	]); ?>

	<?= $form->field($model, 'id') ?>

	<?= $form->field($model, 'userId') ?>

	<?= $form->field($model, 'eventId') ?>

	<?= $form->field($model, 'problemTitle') ?>

	<?= $form->field($model, 'problemDescription') ?>

	<?php // echo $form->field($model, 'imgId1') ?>

	<?php // echo $form->field($model, 'imgId2') ?>

	<?php // echo $form->field($model, 'imgId3') ?>

	<?php // echo $form->field($model, 'problemPage') ?>

	<?php // echo $form->field($model, 'status') ?>

	<?php // echo $form->field($model, 'important') ?>

	<?php // echo $form->field($model, 'response') ?>

	<?php // echo $form->field($model, 'requestDate') ?>

	<?php // echo $form->field($model, 'statusChangeDate') ?>

	<?php // echo $form->field($model, 'valid') ?>

	<div class="form-group">
		<?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
		<?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
	</div>

	<?php ActiveForm::end(); ?>

</div>

backend/modules/ProblemReports/views/problem-reports/create.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\modules\ProblemReports\models\ProblemReports */

$this->title = Yii::t ( 'app', 'Create Problem Reports' );
$this->params ['breadcrumbs'] [] = [ 
		'label' => Yii::t ( 'app', 'Problem Reports' ),
		'url' => [ 
				'index' 
		] 
];
$this->params ['breadcrumbs'] [] = $this->title;
?>
<div class="problem-reports-create">
	<div
		class="col-lg-10 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-12">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="portlet light bordered">
			
			<div class="portlet-body form">

	<?=$this->render ( '_form', [ 'model' => $model ] )?>

</div>
		</div>
		<!-- END SAMPLE FORM PORTLET-->
	</div>
</div>

backend/modules/ProblemReports/views/problem-reports/indexRequest.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\web\View;
use yii\helpers\Url;

use backend\modules\ProblemReports\models\ProblemReports;
/* @var $this yii\web\View */
/* @var $searchModel backend\modules\ProblemReports\models\ProblemReportsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t ( 'app', 'Problem Reports' );
$this->params ['breadcrumbs'] [] = $this->title;

$this->params ['actions'] = [ 
		[ 
				'label' => '<i class="ace-icon fa fa-plus bigger-120 orange"></i> ' . Yii::t ( 'app', 'Create Problem Reports' ),
				'url' => [ 
						'create' 
				] 
		] 
];
?>
<div class="col-md-12 col-sm-12">
	<div class="portlet light ">
		<div class="portlet-title">
			<div class="caption caption-md">
				<i class="icon-bar-chart font-green"></i> <span
					class="caption-subject font-green bold uppercase"><?= $this->title; ?></span>
			</div>
			<div class="actions">
				<div class="btn-group">
					<a class="btn green btn-sm" href="javascript:;"
						data-toggle="dropdown" data-hover="dropdown"
						data-close-others="true"> 
                                            	<?php echo Yii::t('app','More ProblemReports');?>
                                                <i
						class="fa fa-angle-down"> </i>
					</a>
					<ul class="dropdown-menu pull-right">
						<li>
                                                <?php echo Html::a(Yii::t('app','Admin ProblemReports'),Url::to('admin'));?>
                         </li>
						<li class="divider"></li>
						<li>
                                                	<?php echo Html::a(Yii::t('app','All ProblemReports'),Url::to('index'));?>
                                                </li>
						<li>
                                                <?php
																																																$str = ProblemReports::StatusFa ( ProblemReports::Status_Unread );
																																																$str .= '<span class="badge badge-danger">' . ProblemReports::CountStatus ( ProblemReports::Status_Unread ) . '</span>';
																																																echo Html::a ( $str, Url::to ( [ 
																																																		'index',
																																																		'status' => ProblemReports::Status_Unread 
																																																] ) );
																																																?>
                                                </li>

						<li>
                                                <?php
																																																$str = ProblemReports::StatusFa ( ProblemReports::Status_Read );
																																																$str .= '<span class="badge badge-warning">' . ProblemReports::CountStatus ( ProblemReports::Status_Read ) . '</span>';
																																																echo Html::a ( $str, Url::to ( [ 
																																																		'index',
																																																		'status' => ProblemReports::Status_Read 
																																																] ) );
																																																?>
                                                </li>


						<li>
                                                 <?php
																																																	$str = ProblemReports::StatusFa ( ProblemReports::Status_Pending );
																																																	$str .= '<span class="badge badge-info">' . ProblemReports::CountStatus ( ProblemReports::Status_Pending ) . '</span>';
																																																	echo Html::a ( $str, Url::to ( [ 
																																																			'index',
																																																			'status' => ProblemReports::Status_Pending 
																																																	] ) );
																																																	?>
                                                </li>
					</ul>
				</div>
			</div>
		</div>
		<div class="portlet-body">

			<div class="row">

				<div class="mt-element-list">

					<div class="mt-list-container list-todo opt-2">
						<div class="list-todo-line bg-red"></div>
						<ul>
						<?php
						$i = 0;
						foreach ( $models as $model ) {
							$i ++;
							$itemName = 'item-' . $i;
							$id = "task-3-" . $i;
							?>
							
								<li class="mt-list-item">
								<div class="list-todo-icon bg-white font-yellow-crusta">
									<i class="fa fa-sticky-note-o"></i>
								</div>
								<div class="list-todo-item <?= $itemName ?>">
									<a class="list-toggle-container font-white"
										data-toggle="collapse" href="#<?=$id?>" aria-expanded="false">
										<div class="list-toggle done uppercase bg-yellow-crusta">
											<div class="list-toggle-title bold">Content Development</div>
											<div
												class="badge badge-default pull-right bg-white font-dark bold">2</div>
										</div>
									</a>
									<div class="task-list panel-collapse collapse" id="<?=$id;?>">
										<ul>
											<li class="task-list-item done">
												<div class="task-icon">
													<a href="javascript:;"> <i class="fa fa-navicon"></i>
													</a>
												</div>
												<div class="task-status">
													<a class="done" href="javascript:;"> <i class="fa fa-check"></i>
													</a> <a class="pending" href="javascript:;"> <i
														class="fa fa-close"></i>
													</a>
												</div>
												<div class="task-content">
													<h4 class="uppercase bold">
														<a href="javascript:;"><?php echo  $model->requestDateFa;?></a>
													</h4>
													<p><?php echo  $model->problemTitle;?></p>
												</div>
											</li>
											<li class="task-list-item">
												<div class="task-icon">
													<a href="javascript:;"> <i class="fa fa-cube"></i>
													</a>
												</div>
												<div class="task-status">
													<a class="done" href="javascript:;"> <i class="fa fa-check"></i>
													</a> <a class="pending" href="javascript:;"> <i
														class="fa fa-close"></i>
													</a>
												</div>
												<div class="task-content">
													<h4 class="uppercase bold">
														<a href="javascript:;"><?php echo  $model->statusChangeDateFa;?></a>
													</h4>
													<p><?php echo  $model->response;?></p>
												</div>
											</li>
										</ul>
										<div class="task-footer bg-grey">
											<div class="row">
												<div class="col-xs-6">
													<a class="task-trash" href="javascript:;"> <i
														class="fa fa-trash"></i>
													</a>
												</div>
												<div class="col-xs-6">
													<a class="task-add" href="javascript:;"> <i
														class="fa fa-plus"></i>
													</a>
												</div>
											</div>
										</div>
									</div>
								</div>
							</li>
							
							
							<?php
						}
						
						?>
						
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

backend/modules/ProblemReports/views/problem-reports/indexResponse.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\web\View;
use yii\helpers\Url;

use backend\modules\ProblemReports\models\ProblemReports;
/* @var $this yii\web\View */
/* @var $searchModel backend\modules\ProblemReports\models\ProblemReportsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Problem Reports');
$this->params['breadcrumbs'][] = $this->title;

$this->params['actions'] = [
		[
				'label' => '<i class="ace-icon fa fa-plus bigger-120 orange"></i> ' . Yii::t('app', 'Create Problem Reports'),
				'url' => ['create']
		]
];
?>
<div class="col-md-12 col-sm-12">
	<div class="portlet light ">
		<div class="portlet-title">
			<div class="caption caption-md">
				<i class="icon-bar-chart font-green"></i> <span
					class="caption-subject font-green bold uppercase"><?= $this->title; ?></span>
				
			</div>
			<div class="actions">
						 <div class="btn-group">
                                            <a class="btn green btn-sm" href="javascript:;" data-toggle="dropdown" data-hover="dropdown" data-close-others="true"> 
                                            	<?php echo Yii::t('app','More ProblemReports');?>
                                                <i class="fa fa-angle-down"></i>
                                            </a>
                                            <ul class="dropdown-menu pull-right">
                                                <li>
                                                <?php echo Html::a(Yii::t('app','Admin ProblemReports'),Url::to('admin'));?>
                                                </li>
                                                <li class="divider"> </li>
                                                <li>
                                                	<?php echo Html::a(Yii::t('app','All ProblemReports'),Url::to('index'));?>
                                                </li>
                                                <li>
                                                <?php
	                                                $str=ProblemReports::StatusFa(ProblemReports::Status_Unread);
	                                                $str.='<span class="badge badge-danger">'. ProblemReports::CountStatus(ProblemReports::Status_Unread).'</span>';
	                                                echo Html::a($str,Url::to(['index','status'=>ProblemReports::Status_Unread]));
                                                ?>
                                                </li>
                                                
                                                 <li>
                                                <?php
	                                                $str=ProblemReports::StatusFa(ProblemReports::Status_Read);
	                                                $str.='<span class="badge badge-warning">'. ProblemReports::CountStatus(ProblemReports::Status_Read).'</span>';
	                                               echo Html::a($str,Url::to(['index','status'=>ProblemReports::Status_Read]));
                                                ?>
                                                </li>
                                                
                                                
                                                <li>
                                                 <?php
	                                                $str=ProblemReports::StatusFa(ProblemReports::Status_Pending);
	                                                $str.='<span class="badge badge-info">'. ProblemReports::CountStatus(ProblemReports::Status_Pending).'</span>';
	                                                echo Html::a($str,Url::to(['index','status'=>ProblemReports::Status_Pending]));
                                                ?>
                                                </li>
                                            </ul>
                                        </div>
			</div>
		</div>
		<div class="portlet-body">
			<div class="scroller" style="height: 100%;" data-always-visible="1"
				data-rail-visible1="0" data-handle-color="#D7DCE2">
				<div class="general-item-list">
                                        <?php
                                        foreach ( $models as $model ) {
                                        ?>
                                        	 <div class="item">
												<div class="item-head">
													<div class="item-details">
														<img class="item-pic rounded"
															src="../assets/pages/media/users/avatar4.jpg"> <a href=""
															class="item-name primary-link"><?= $model->userId?></a> <span
															class="item-label"><?php echo  $model->requestDateFa;?></span>
													</div>
													<span class="item-status">
                                                      <?php echo  $model->statusUI;?>
                                                       <?php echo ProblemReports::StatusFa ( $model->status );?>
						                            </span>
												</div>
												<div class="item-body"> <?php echo  $model->problemTitle;?></div>
												<div class='row'>
												 	<div class="form-group">
													 	<div class="col-md-10"></div>
													 	<div class="col-md-2">
													 	<?php 
				                                           echo  Html::a('<i class="icon-pencil"></i>', Url::to(['update','id' => $model->id]), [
				                                            		'title' => Yii::t ( 'app', 'Update' ),
				                                            		'data-hint' =>Yii::t ( 'app', 'Update' ),
				                                            		'class' => 'btn btn-icon-only btn-default hint--top hint--rounded hint--info'
				                                            ])
				                                        ?>
				                                        	<?php 
				                                           echo  Html::a('<i class="glyphicon glyphicon-eye-open"></i>', Url::to(['view','id' => $model->id]), [
				                                            		'title' => Yii::t ( 'app', 'View' ),
				                                            		'data-hint' =>Yii::t ( 'app', 'View' ),
				                                            		'class' => 'btn btn-icon-only btn-default hint--top hint--rounded hint--info'
				                                            ])
				                                        ?>
				                                         </div>
                                        			</div>
                                    			</div>
												</div>
                                        <?php } ?>
              </div>
			</div>
			
			
		</div>
	</div>
</div>