backend/controllers/MembersController.php
<?php

namespace backend\controllers;


use Yii;
use backend\models\User;
use backend\models\UserSearch;
use backend\models\Userd;
use backend\models\UserdSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use \yii\helpers\Json;
use yii\helpers\Url;
use backend\models\ChangePassword;
use yii\web\UploadedFile;


/**
 * UserController implements the CRUD actions for User model.
 */
class MembersController extends Controller
{

	/* ID for Access control */
	public $currentEventId;
	public $currentUserDetailId;
	public $currentEventName;
	public $userId;

	public $_eventObj;
	public $_carvanObj;
	public $_teamObj;
	public $_universityObj;
	public $_authorizedFieldObj;
	public $_universityRespUserObj;
	public $_universityId;

   public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				//'only' => ['login', 'logout', 'signup','index'],
				'rules' => [
						[
								'allow' => true,
								'actions' => ['profileinfo','update-user','updateinfo','profileview','remove'],
								'roles' => ['admin','supervisor','student'],
						],
						[
								'allow' => true,
								'actions' => ['update-user','updateinfo','profileview'],
								'roles' => ['student'],
						],
				],
			],
		];
	}


	public function actionProfileinfo()
    {
        $message = '';

        /*-----View Info Code------*/
        $curentUserId = isset(\Yii::$app->user->identity->id) ? \Yii::$app->user->identity->id : 0;
        $curentUserdModel = Userd::find()->andWhere(['user_id' => $curentUserId])->one();
        //die(var_dump($curentUserId1->id));
        if (!$curentUserId) {
            throw new \yii\web\HttpException(400, Yii::t('app', 'You are not authorized to per-form this action.you just can view your Information'));
        }

		 

		$userModel = $this->findModel($curentUserId);
        //$userModel1 = $this->findModel($curentUserId1);
        //die(var_dump($curentUserId1));


        return $this->render('manage_profile_info', array(
					'model' => $userModel ,
                    'modeld' => $curentUserdModel ,
				   // 'loginModel' => $loginModel,
						'message' => $message,
		));

	}



	public function actionProfileview($id) {
		$message='';
	    $model=$this->findModel($id);
		$model->scenario='UpdateProfileInfo';  
		
		if ($model->load(Yii::$app->request->post())&&(isset($_POST['update_prsonal_info_btn'])||isset($_POST['update_prsonal_info_btn_byadmin']))) 
		{ 

			if(isset($_POST['update_prsonal_info_btn_byadmin'])){
				$model->readonly = 1;
			}
			if($model->save(false)){
				 
				$message=$this->createMessageCss('success', Yii::t('app', '{item} Successfully Edited.', ['item' => Yii::t('app', 'User')]) );
			}
			 
		}
		/**----------------------------------**/
		
		
	/**--------Update Picture -----------**/
	if ($model->load(Yii::$app->request->post())&&isset($_POST['update_pic_btn'])) 
	{
			$image = UploadedFile::getInstances($model, 'fileAttr')[0];
			$image1 = UploadedFile::getInstances($model, 'fileAttr1')[0];
			$image2 = UploadedFile::getInstances($model, 'fileAttr2')[0];
			$image3 = UploadedFile::getInstances($model, 'fileAttr3')[0];
			// store the source file name
            //$model->fileId = $image->name."pic".$model->id;
			$name=$image->name;
			$pieces = explode(".", $name);
			$name=$pieces[1];	
			$user=$model->username;
			
			$name1=$image1->name;
			$pieces = explode(".", $name1);
			$name1=$pieces[1];	
			
			$name2=$image2->name;
			$pieces = explode(".", $name2);
			$name2=$pieces[1];	
			
			$name3=$image3->name;
			$pieces = explode(".", $name3);
			$name3=$pieces[1];	
			
			
            //$ext = end((explode(".", $name1)));
			$ext='jpg';
			//die(var_dump($image));

            // generate a unique file name
            //$avatar = Yii::$app->security->generateRandomString().".{$ext}";

            // the path to save file, you can set an uploadPath
            // in Yii::$app->params (as used in example below)
            $path = Yii::$app->basePath . '/uploads/' . $user.'_image.'.'jpg';
			$path1 = Yii::$app->basePath . '/uploads/' . $user.'_id1.'.$name1;
			$path2 = Yii::$app->basePath . '/uploads/' . $user.'_id2.'.$name2;
			$path3 = Yii::$app->basePath . '/uploads/' . $user.'_naca.'.$name3;

            if($model->save(false))
            {
				if($model->validate(['fileAttr','fileAttr1','fileAttr2','fileAttr3'])&&$model->save(false))
				{
					if($image)$image->saveAs($path);
					if($image1)$image1->saveAs($path1);
					if($image2) $image2->saveAs($path2);
					if($image3)$image3->saveAs($path3);

					$message=$this->createMessageCss('success',Yii::t('app', 'تصویر با موفقیت بارگذاری شد.'));
					//$this->setFlashMsg('success',$message);
					//return $this->redirect(['members/profileview', 'id'=>$model->id,'#'=>'tab_1_2']);

				}

            } 
            else 
            {
				$message=$this->createMessageCss('success',Yii::t('app', 'اشکالی در بارگذاری فایل بوجود آمده است.'));
            }
	}
	/**-----------------------------------**/	   
	  
	/**-----------------------------changePassword ------------------------------------------------**/
	$changePasswordModel = new ChangePassword(['scenario'=>'change_password_byadmin']);
	$changePasswordModel->username = Yii::$app->user->identity->username;
	$changePasswordModel->passwordInput=  isset($_POST['ChangePassword']['passwordInput'])?$_POST['ChangePassword']['passwordInput']:'';
	$changePasswordModel->targetUser = (int) $id;

	if ($changePasswordModel->load(Yii::$app->request->post())&&isset($_POST['change_pass_btn'])) { 


		if ($changePasswordModel->load(Yii::$app->request->post()) ) {
			//die(var_dump($changePasswordModel->validate()));
			/*---check Password----*/
			if ($resultValidate=$changePasswordModel->validate() && $resultVerifyPass=$changePasswordModel->ValidateCurrentPassword())
			{
				if ($changePasswordModel->changePassword())
				{
					$message=$this->createMessageCss('success',Yii::t('app', 'کلمه عبور با موفقیت تغییر کرد.'));
				}
				else{
					$message=$this->createMessageCss('error',Yii::t('app', 'اشکالی در فرآیند تغییر کلمه عبور بوجود آمده است.'));
				}
				//$this->setFlashMsg('success',$message);
				//return $this->redirect(['members/profileview', 'id'=>$model->id,'#'=>'tab_1_2']);

			}
			elseif (!$resultValidate || !$resultVerifyPass)
			{
					$message=$this->createMessageCss('error',Yii::t('app', 'Error in changed password!'));
			}
		}

	}
	/**-----------------------------------------------------------------------------------------------**/  


        $curentUserdModel = Userd::find()->andWhere(['user_id' => $id])->one();

		return $this->render('update_user', [
					'model' =>$model,
					'massage' => $message,
                    'model1' => $curentUserdModel ,
					//'userDetails'=>$userDetails,
					'changePasswordModel'=>$changePasswordModel

		]);
	}



	public function actionRemove()
    {
		$admin 				= Yii::$app->user->can('admin');
		$supervisor			= Yii::$app->user->can('supervisor');
		$student 			= Yii::$app->user->can('student');

		$curentUserId = isset(\Yii::$app->user->identity->id) ? \Yii::$app->user->identity->id : 0;

		$userId=(int)$_GET['user_id'];
		$model = User::find()->andWhere(['id' => $userId])->one();

		if($student)
		{
			if($userId!=$curentUserId)
			{
				throw new \yii\web\HttpException(400, Yii::t('You are not authorized to per-form this action.you just can view your Information'));

			}

		}

		$type=$_GET['data'];

		if(!in_array($type,['_image','_id1','_id2','_naca']))
		{
			throw new \yii\web\HttpException(400, Yii::t('You are not authorized to per-form this action.you just can view your Information'));

		}

		$filename = '../uploads/'. $model->username.$type.'.jpg';

        unlink($filename);

		return $this->redirect(['members/profileview', 'id'=>$userId]);

	}
	public function actionUpdateUser($userId) 
	{
		$message='';
		
		$curentUserId = isset(\Yii::$app->user->identity->id) ? \Yii::$app->user->identity->id : 0;
        $model1=Userd::find()->andWhere(['user_id'=>$curentUserId])->one();
        if (!$curentUserId) {
			throw new \yii\web\HttpException(400, Yii::t('You are not authorized to per-form this action.you just can view your Information'));
		}
		$userId= $curentUserId;

 
		$model=$this->findModel($userId);
		$model->scenario='UpdateProfileInfo';  
		$model1->scenario='UpdateProfileInfo1';

        //die(var_dump($model));
		
		/**-------Update Personal info-------**/
		if ($model->load(Yii::$app->request->post())&& $model1->load(Yii::$app->request->post())&& isset($_POST['update_prsonal_info_btn']) ) {

			if(!$model->readOnly)
			{
				if( $model->save())	{
					$model1->save();

				}

			}else
			{
				$model->addError('name','You cant edit information after admin confirmation');
			}

				$message=$this->createMessageCss('success', Yii::t('app', '{item} Successfully Edited.', ['item' => Yii::t('app', 'User')]) );
		}
		/**----------------------------------**/


	/**--------Update Picture -----------**/
	if ($model->load(Yii::$app->request->post())&&isset($_POST['update_pic_btn']))
	{
            $image= UploadedFile::getInstance($model, 'fileAttr');
            $image1= UploadedFile::getInstance($model, 'fileAttr1');
            $image2 = UploadedFile::getInstance($model, 'fileAttr2');
            $image3 = UploadedFile::getInstance($model, 'fileAttr3');

			$user=$model->username;
            $path = Yii::$app->basePath . '/uploads/' . $user.'_image.'.'jpg';
			$path1 = Yii::$app->basePath . '/uploads/' . $user.'_id1.'.'jpg';
			$path2 = Yii::$app->basePath . '/uploads/' . $user.'_id2.'.'jpg';
			$path3 = Yii::$app->basePath . '/uploads/' . $user.'_naca.'.'jpg';

            if($model->validate(['fileAttr','fileAttr1','fileAttr2','fileAttr3'])&&$model->save(false))
            {
                if($image)$image->saveAs($path);
                if($image1)$image1->saveAs($path1);

backend/views/members/_change_password_user_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* * *select2 uses*** */
use kartik\select2\Select2;
use yii\web\JsExpression;
use yii\helpers\ArrayHelper;
use app\models\Language;
use yii\web\View;

/* @var $this yii\web\View */
/* @var $model app\models\Countries */
/* @var $form yii\widgets\ActiveForm */
?>
<div id="results_change_pass"  >

</div>
<div>
	<?php yii\widgets\Pjax::begin(['id' => 'change_pass_pjax']) ?>
	<?php echo $message ?>
	<?php
	// var_dump($message);
	/* ------------show flash messages----------------- */
//	$session = Yii::$app->session;
//   // check the availability
//	$result = $session->hasFlash('change_password_success');
//   // get and display the message
//	echo $session->getFlash('change_password_success');
	?>
	<?php $form = ActiveForm::begin(['options' => ['data-pjax' => true, 'id' => 'form_change_pass']]); ?>
	<?php echo $form->errorSummary([$model]); ?>

	<div class="form-group col-xs-6"> 
		<?php
		$model->inputNewPassword = '';
		echo $form->field($model, 'inputNewPassword')->passwordInput(['maxlength' => 255, 'autocomplete' => 'off'])
		?>
	</div>
	<div class="form-group col-xs-6"> 
		<?php
		$model->inputNewPassword_repeat = '';
		echo $form->field($model, 'inputNewPassword_repeat')->passwordInput(['maxlength' => 255, 'autocomplete' => 'off'])
		?>
	</div>


	<div class="form-group">
		<input type="submit" name="submitBtn" class = "btn btn-sb" value="<?= Yii::t('app', 'Confirm') ?>"id="submit_btn">
	<?php //Html::submitButton(Yii::t('app', 'Create'), ['class' => 'btn btn-success','id'=>'submit_btn','name'=>'btnSubmit'])   ?>
	</div>

<?php ActiveForm::end(); ?>
<?php yii\widgets\Pjax::end() ?>

</div>

backend/views/members/_update_athlete_change_pic.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/***select2 uses****/
use  yii\web\View;

use kartik\file\FileInput;
use yii\helpers\Url;
$formGroupClass = Yii::$app->params ['formGroupClass'];
$template = '{label}<div class="col-md-8 col-sm-8">{input} {hint} {error}</div>';
$inputClass = Yii::$app->params ['inputClass'];
$labelClass = 'col-md-3';
$errorClass = Yii::$app->params ['errorClass'];
?>

<div class="tab-pane" id="tab_1_2">

	
												   
														
	<?php $uploadForm = ActiveForm::begin(['options' => ['id'=>'form_change_pic','data-pjax' => true,  'role'=>'form','enctype' => 'multipart/form-data', 'class' => 'form-horizontal']]); ?>
	<?php echo $uploadForm->errorSummary([$model], ['class' => 'alert alert-danger']);  ?>
    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
	                <?php
	                echo $uploadForm->field($model, 'fileAttr')->widget(FileInput::classname(), [
	                    'id' => 'file_input_user_pic',
	                    'language' => 'fa',
	                    'options' => [
	                        'multiple' => true,
	                        'layoutTemplates' => 'modal',
	                    ],
	                    'pluginOptions' => [
							'showUpload' => false,
							'maxFileCount' => 1,
							'msgInvalidFileExtension'=>Yii::t('app','Invalid extension for file . Only "{extensions}" files are supported.'),
							'allowedFileExtensions'=>$model->fileExtentionsArr,
							'msgSizeTooLarge'=>Yii::t('app','File  ({size} KB) exceeds maximum allowed upload size of {maxSize} KB. Please retry your upload!'),
							'maxFileSize'=>$model->fileSizeKB,
							'previewFileType' => 'image',

						]
	                ]);				
	                ?>
        </div>
        <div class="col-md-1 col-sm-6 col-xs-12">
                   <?php

                    $user=$model->username;
                    $filename = '../uploads/'. $user.'_image.jpg';
                    $url=Url::to(['members/remove']);
                    if(file_exists($filename)) {
                        // echo '<a href="'.$url.'">'.'حذف تصویر'.'</a>';
                        echo '<br>';
                        echo Html::a('حذف', ['/members/remove', 'data' => '_image', 'user_id' => $model->id], ['name' => 'image', 'class' => 'btn btn-primary']);
                    }



                   ?>
        </div>
        <div class="col-md-4 col-sm-6 col-xs-12">

                    <?php
                    if(is_object($model))
                    {
                        $user=$model->username;
                        $path=Yii::$app->request->BaseUrl.'/../uploads/'. $user.'_image.jpg';
                        echo Html::img($path,[
                            "height"=>"50px",
                            "width"=>"50px",
                            "class"=>'profile-userpic profile-oldpic',
                        ]);
                    }
                    ?>
        </div></div>
    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
					<?php
	                echo $uploadForm->field($model, 'fileAttr1')->widget(FileInput::classname(), [
	                    'id' => 'file_input_user_pic',
	                    'language' => 'fa',
	                    'options' => [
	                        'multiple' => true,
	                        'layoutTemplates' => 'modal',
	                    ],
	                    'pluginOptions' => [
							'showUpload' => false,
							'maxFileCount' => 1,
							'msgInvalidFileExtension'=>Yii::t('app','Invalid extension for file . Only "{extensions}" files are supported.'),
							'allowedFileExtensions'=>$model->fileExtentionsArr,
							'msgSizeTooLarge'=>Yii::t('app','File  ({size} KB) exceeds maximum allowed upload size of {maxSize} KB. Please retry your upload!'),
							'maxFileSize'=>$model->fileSizeKB,
							'previewFileType' => 'image',

						]
	                ]);	
					?>
        </div>
        <div class="col-md-1 col-sm-6 col-xs-12">
                    <?php
                    $user=$model->username;
                    $filename = '../uploads/'. $user.'_id1.jpg';
                    $url=Url::to(['members/remove']);
                    if(file_exists($filename))
                    {
                        // echo '<a href="'.$url.'">'.'حذف تصویر'.'</a>';
                        echo  Html::a('حذف', ['/members/remove',  'data' => '_id1','user_id'=>$model->id], ['name'=>'image','class' => 'btn btn-primary']);
                        //echo' <input type="submit" name="tt" value="ff" class="btn btn-primary">';
                    }
                    ?>
        </div>
        <div class="col-md-4 col-sm-6 col-xs-12">

            <?php
            if(is_object($model))
            {
                $user=$model->username;
                $path=Yii::$app->request->BaseUrl.'/../uploads/'. $user.'_id1.jpg';
                echo Html::img($path,[
                    "height"=>"50px",
                    "width"=>"50px",
                    "class"=>'profile-userpic profile-oldpic',
                ]);
            }
            ?>
        </div></div>
    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
					<?php
	                echo $uploadForm->field($model, 'fileAttr2')->widget(FileInput::classname(), [
	                    'id' => 'file_input_user_pic',
	                    'language' => 'fa',
	                    'options' => [
	                        'multiple' => true,
	                        'layoutTemplates' => 'modal',
	                    ],
	                    'pluginOptions' => [
							'showUpload' => false,
							'maxFileCount' => 1,
							'msgInvalidFileExtension'=>Yii::t('app','Invalid extension for file . Only "{extensions}" files are supported.'),
							'allowedFileExtensions'=>$model->fileExtentionsArr,
							'msgSizeTooLarge'=>Yii::t('app','File  ({size} KB) exceeds maximum allowed upload size of {maxSize} KB. Please retry your upload!'),
							'maxFileSize'=>$model->fileSizeKB,
							'previewFileType' => 'image',

						]
	                ]);				
	                ?>
        </div>
        <div class="col-md-1 col-sm-6 col-xs-12">
                    <?php
                    $user=$model->username;
                    $filename = '../uploads/'. $user.'_id2.jpg';
                    $url=Url::to(['members/remove']);
                    if(file_exists($filename))
                    {
                        // echo '<a href="'.$url.'">'.'حذف تصویر'.'</a>';
                        echo  Html::a('حذف', ['/members/remove',  'data' => '_id2','user_id'=>$model->id], ['name'=>'image','class' => 'btn btn-primary']);
                        //echo' <input type="submit" name="tt" value="ff" class="btn btn-primary">';
                    }
                    ?>
        </div>
        <div class="col-md-4 col-sm-6 col-xs-12">

            <?php
            if(is_object($model))
            {
                $user=$model->username;
                $path=Yii::$app->request->BaseUrl.'/../uploads/'. $user.'_id2.jpg';
                echo Html::img($path,[
                    "height"=>"50px",
                    "width"=>"50px",
                    "class"=>'profile-userpic profile-oldpic',
                ]);
            }
            ?>
        </div></div>
    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
					<?php
	                echo $uploadForm->field($model, 'fileAttr3')->widget(FileInput::classname(), [
	                    'id' => 'file_input_user_pic',
	                    'language' => 'fa',
	                    'options' => [
	                        'multiple' => true,
	                        'layoutTemplates' => 'modal',
	                    ],
	                    'pluginOptions' => [
							'showUpload' => false,
							'maxFileCount' => 1,
							'msgInvalidFileExtension'=>Yii::t('app','Invalid extension for file . Only "{extensions}" files are supported.'),
							'allowedFileExtensions'=>$model->fileExtentionsArr,
							'msgSizeTooLarge'=>Yii::t('app','File  ({size} KB) exceeds maximum allowed upload size of {maxSize} KB. Please retry your upload!'),
							'maxFileSize'=>$model->fileSizeKB,
							'previewFileType' => 'image',

						]
	                ]);				
	                ?>
        </div>
        <div class="col-md-1 col-sm-6 col-xs-12">
                    <?php
                    $user=$model->username;
                    $filename = '../uploads/'. $user.'_naca.jpg';
                    $url=Url::to(['members/remove']);
                    if(file_exists($filename))
                    {
                        // echo '<a href="'.$url.'">'.'حذف تصویر'.'</a>';
                        echo  Html::a('حذف', ['/members/remove',  'data' => '_naca','user_id'=>$model->id], ['name'=>'image','class' => 'btn btn-primary']);
                        //echo' <input type="submit" name="tt" value="ff" class="btn btn-primary">';
                    }
                    ?>
        </div>
        <div class="col-md-4 col-sm-6 col-xs-12">

            <?php
            if(is_object($model))
            {
                $user=$model->username;
                $path=Yii::$app->request->BaseUrl.'/../uploads/'. $user.'_naca.jpg';
                echo Html::img($path,[
                    "height"=>"50px",
                    "width"=>"50px",
                    "class"=>'profile-userpic profile-oldpic',
                ]);
            }
            ?>
        </div></div>

        <div class="row">
            <div class="margiv-top-10">
                <?= Html::submitButton(Yii::t('app', 'ارسال'), ['name' => 'update_pic_btn', 'class' => 'btn green']) ?>
                <?php //echo Html::submitButton(Yii::t('app', 'Cancel'), ['class' => 'btn default']) ?>
            </div>
        </div>

   <?php ActiveForm::end(); ?>
	
</div>


<script>
	 function savePicture()
	{

		var _form = $('#form_change_pic');
		var _successmsg = "<?php echo Yii::t('app', '{item} Successfully Edited.', ['item' => Yii::t('app', 'File')]) ?>"
		var _failmsg = "<?php echo Yii::t('app', 'Failed To Edit Items To {item}.', ['item' => Yii::t('app', 'File')]) ?>"

		var formData = new FormData($('#form_change_pic')[0]);
		formData.append('file', $('input[type=file]')[0].files[0]);

		$.ajax({
			type: _form.attr('method'),
			url: _form.attr('action'),
			data: formData,
			processData: false,
			contentType: false,
			dataType: "JSON",
			success: function (data) {

				/**success save**/
				if ((typeof data.success === true))
				{

		   
					/*provide success Message */
					$("#results_expand_msg" ).html("<div class=\"alert alert-success\" role=\"alert\"> " + _successmsg + " </div>");

					/*
					 *1-fade success message
					 *2-close detailview div slidly
					 *3-reload gridview by pjax 
					 */
					$("#results_expand_msg").fadeIn(3500, function () {
					$("#results_expand_msg").fadeOut( 4000 );
					});

				} else  /***********fail save *****************/
				{
			   
					/*provide success Message */
					$("#results_expand_msg" ).html("<div class=\"alert alert-danger\" role=\"alert\"> " + data.errormessage + " </div>");


					$("#results_expand_msg" ).fadeIn(1300, function () {
//					   // $.pjax.reload({container: "#Projects"});
					});
				}



			},
			error: function (data) {

				alert(_failmsg);

			}
		});


	}
	</script>

<!--														<form action="#" role="form">
															<div class="form-group">
																<div class="fileinput fileinput-new" data-provides="fileinput">
																	<div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
																		<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt=""> </div>
																	<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"> </div>
																	<div>
																		<span class="btn default btn-file">
																			<span class="fileinput-new"> Select image </span>
																			<span class="fileinput-exists"> Change </span>
																			<input type="file" name="..."> </span>
																		<a href="javascript:;" class="btn default fileinput-exists" data-dismiss="fileinput"> Remove </a>
																	</div>
																</div>
																<div class="clearfix margin-top-10">
																	<span class="label label-danger">NOTE! </span>
																	<span>Attached image thumbnail is supported in Latest Firefox, Chrome, Opera, Safari and Internet Explorer 10 only </span>
																</div>
															</div>
															<div class="margin-top-10">
																<a href="javascript:;" class="btn green"> Submit </a>
																<a href="javascript:;" class="btn default"> Cancel </a>
															</div>
														</form>-->

backend/views/members/manage_profile_info.php
<?php

use yii\helpers\Html;
use backend\assets\UserProfile;





UserProfile::register($this);


/* @var $this yii\web\View */
/* @var $model app\models\Fields */

$this->title = Yii::t('app', 'Profile');

$this->params['breadcrumbs'][] = $this->title;
?>
					
					<div class="row">
						<div class="col-md-12">
							<!-- BEGIN PROFILE SIDEBAR -->
							<div class="profile-sidebar">
								<!-- PORTLET MAIN -->
								<div class="portlet light profile-sidebar-portlet ">
									<!-- SIDEBAR USERPIC -->
									<div class="profile-userpic">
									 <?php
									 if(is_object($model))
									 {
										 $user=$model->username;
										 $path=Yii::$app->request->BaseUrl.'/../uploads/'. $user.'_image.jpg';
										echo Html::img($path);
									 }
									 ?>			 
									</div>
									<!-- END SIDEBAR USERPIC -->
									<!-- SIDEBAR USER TITLE -->
									<div class="profile-usertitle" id="user_quick_info">
										<div class="profile-usertitle-name"> <?php echo Html::encode($model->FullName)?></div>
										<div class="profile-usertitle-job"> <?php echo Html::encode($model->nationalId)?> </div>
									</div>
									<!-- END SIDEBAR USER TITLE -->
									<!-- SIDEBAR BUTTONS -->
									<div class="profile-userbuttons">
										<?php $space='&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'?>
										<?php echo Html::a($space.Yii::t('app','Edit').$space, \yii\helpers\Url::to(['/members/update-user','userId'=>$model->id],true),['class'=>"btn green btn-sm"]);?>
										<?php //echo Html::a($space.Yii::t('app','Change Password').$space, \yii\helpers\Url::to(['YumUsers/members/update-user','userId'=>$model->id],true),['class'=>"btn red btn-sm"]);?>
									</div>
									<!-- END SIDEBAR BUTTONS -->
									<!-- SIDEBAR MENU -->
									<div class="profile-usermenu">

									</div>
									<!-- END MENU -->
								</div>
								<!-- END PORTLET MAIN -->

							</div>
							<!-- END BEGIN PROFILE SIDEBAR -->
							<!-- BEGIN PROFILE CONTENT -->
													   <?php

														echo $this->render('user_info_view', [
															'model' => $model,
                                                            'modeld' => $modeld ,

													 
														])

														?>  
								 <!-- END PROFILE CONTENT -->
						</div>
					</div>